apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
type: Opaque
data:
  # Value: "SecretKey..."
  NACOS_AUTH_TOKEN: "U2VjcmV0S2V5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5"
