apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  # Service Identity
  GATEWAY_PORT: "8081"
  
  # Nacos Config
  NACOS_HOST: "nacos"
  NACOS_PORT: "8848"
  NACOS_NAMESPACE: "public"
  NACOS_GROUP: "DEFAULT_GROUP"
  NACOS_LOG_DIR: "/tmp/nacos/log"
  NACOS_CACHE_DIR: "/tmp/nacos/cache"

  # Redis Config
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
