apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  # Service Identity
  AUTH_SERVER_PORT: "50051"
  AUTH_HTTP_PORT: "8082"
  
  # Nacos Config
  NACOS_HOST: "nacos"
  NACOS_PORT: "8848"
  NACOS_NAMESPACE: "public"
  NACOS_GROUP: "DEFAULT_GROUP"
  NACOS_LOG_DIR: "/tmp/nacos/log"
  NACOS_CACHE_DIR: "/tmp/nacos/cache"

  # Database Config
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "casino_db"
  DB_USER: "postgres"
  
  # Redis Config
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
