apiVersion: v1
kind: Secret
metadata:
  name: user-secret
type: Opaque
data:
  JWT_SECRET: "ZGV2LXNlY3JldC1rZXk="
  DB_PASSWORD: "cGFzc3dvcmQ="
  NACOS_AUTH_TOKEN: "U2VjcmV0S2V5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5"
