kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 8088
    listenAddress: "0.0.0.0"
  - containerPort: 30081
    hostPort: 30081
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  # Map Nacos Console (8848) for easy access
  - containerPort: 30848
    hostPort: 18848
    protocol: TCP
  # Map Postgres for host access
  - containerPort: 30432
    hostPort: 15432
    protocol: TCP
  # Mount local folder for persistence
  extraMounts:
  - hostPath: ./deploy/k8s/data
    containerPath: /data
- role: worker
- role: worker
