apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ops-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # 重寫路徑: /ops/foo -> /foo
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /ops(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: ops-service
            port:
              number: 8080
